CHANGELOG.md
transcriptic/__init__.py

Seems logical to add this step since autoprotocol is required by default and this has been done for preview. Will make the functions consistent in terms of the inputs accepted.

Enabled `analyze` and `submit` to work for Protocol objects

---

transcriptic/cli.py

The web app will soon ship a change which individually versions protocols.  These are some small changes to accommodate that diff.  This does not need to be landed until the diff in the web app is live.  See the phab diff and task below.
D3907
T4539

Changes to support individually versioned protocols

---

CHANGELOG.md
setup.py
transcriptic/cli.py

Added
- `launch` command now supports --save_input option to save the protocol input as a local file
Fixed
- `launch` command now properly supported either a project name or project id for the `project` option
- typo AutoProtocol -> Autoprotocol

A few small enhancements for the `launch` command

---

CHANGELOG.md
setup.py
transcriptic/cli.py

- This results in QuickLaunch configuration screens maintaining input ordering as defined in the manifest

Deserializing manifest into OrderedDict to preserve key ordering

---

CHANGELOG.md
transcriptic/config.py
transcriptic/routes.py

- Allows users to get a data zipfile by using `api.get_zip`
- This returns a Python [Zipfile](https://docs.python.org/2/library/zipfile.html) filetype, which can then be further processed according to the user's intent

Add api route for getting zipfiles

---

CHANGELOG.md
README.md
transcriptic_complete.sh

Added bash completion to TxPy, which can be enabled by sourcing the `transcriptic_complete.sh`
Also added instructions into the readme for setting this up

Add bash completion to TxPy

---

CHANGELOG.md
transcriptic/config.py

In the past, `api.get_zip` automatically downloaded zip files to memory and returned a Python ZipFile representation. However, when dealing with large zip files, it may not be desirable (or possible) to load the entire file into memory.
This PR fixes the issue by adding a `file_path` option to `get_zip` to enable downloading of big files to a specified local file_path.

Enable downloading of large zip files for api.get_zip

---

CHANGELOG.md
test/api_test.py
transcriptic/cli.py
transcriptic/config.py
transcriptic/routes.py

This PR adds in the `select_org` command to the Python CLI, as well as the User-Agent field to the headers portion of the request.

Adding in `select_org` to CLI and User-Agent

---

transcriptic/cli.py

Fixing quick launch locally, which was expecting a protocol object, not a string as a param to run_protocol

Fixing quick launch locally

---

CHANGELOG.md
setup.py
transcriptic/config.py
transcriptic/routes.py

This adds the `upload_dataset_from_filepath` and `upload_dataset` functions to the `api` object, which allows a user to attach an analysis dataset to a specified run.
Usage examples
```
api.upload_dataset_from_filepath(
"my_file.txt", 
title="my cool dataset",
run_id="r123",
analysis_tool="cool script",
analysis_tool_version="v1.0.0"
)
from io import StringIO
temp_buffer = StringIO()
my_df.to_csv(temp_buffer)
api.upload_dataset(
temp_buffer,
name="my_df",
title="my cool dataset",
run_id="r123",
analysis_tool="cool script",
analysis_tool_version="v1.0.0"
)
```

Add upload_dataset functionality to api object

---

CHANGELOG.md
transcriptic/config.py
transcriptic/jupyter/objects.py

This PR adds the `warp_events` property into Instruction objects. 
Warp events include discrete monitoring events such as liquid sensing events for `liquid_handle` instructions.

Add `warp_events` into Instruction object

---

CHANGELOG.md
transcriptic/cli.py
transcriptic/config.py
transcriptic/routes.py

This PR updates `transcriptic launch` so that one can use the inputs saved from a `--local` launch for launching a run with the remote protocol. 
To preserve the old behavior and also allow for using the saved inputs for a `--local` launch, there has been some additional plumbing added in the CLI and Connection object for converting `raw_inputs` to `inputs`.

Ensure that output of --save_input from `transcriptic launch` is consistent for --local and remote

---

CHANGELOG.md
transcriptic/cli.py

This PR adds a test flag to transcriptic launch, which allows the submission of test runs (using test-containers) via the launch command (similar to launching a test run via transcriptic submit). 
Example: `transcriptic launch Pipetting Pipetting_test.json --project p1advzzu23m4n --test`

Add `--test` flag to `transcriptic launch`

---

MANIFEST.in
setup.py
transcriptic/cli.py
transcriptic/templates/manifest.json.jinja
transcriptic/templates/protocol.py.jinja
transcriptic/templates/requirements.txt.jinja

Summary:
Creating a python protocol can be tough going.  One must understand
autoprotocol-py, the format of the manifest.json, and know which
dependencies are required.
The `generate_protocol` command should make it easier for both new and
old users to get up and running when writing protocols.
Test Plan:
Manually attempt to generate a protocol, and verify that it preview succeeds.
`transcriptic generate_protocol foo`
`transcriptic preview foo`
Reviewers: yangchoo, peter
Differential Revision: https://work.r23s.net/D9168

Add a `generate_protocol` CLI command that inits an example protocol.

---

CHANGELOG.md
CONTRIBUTING.md
setup.py
test/config_test.py
tox.ini
transcriptic/__init__.py
transcriptic/commands.py
transcriptic/config.py
transcriptic/routes.py

- General work on `Connection()`:
- Add testing support to Connection() and endpoints needed by script.
- Added `Connection.from_default_config()` method and tests
- Improved error handling of erroneous `Connection()` startup
- Added shim to help test get/put in this context with injection of `requests.Session` object into parent class for easier testing
- Adding access to the aliquot labels:
- Added api method interface.
- Tested with web backend for aliquot changes.
- General lint and control flow cleanup

Expose Aliquot Endpoint

---

CHANGELOG.md
Dockerfile
README.md
docs/README.rst

Udates the relevant email address to be in sync with the shift of domain names

Update email references to point to strateos

---

setup.py

Unfortunately, while tox, pip and other tools can support the wildcard specification format, pypi legacy doesn't seem to be able to support wildcard specification.
This updates the setup.py requirements formatting to equivalently similar package version ranges.

Change versioning format for pypi compatibility

---

CHANGELOG.md
test/cli_test.py
transcriptic/cli.py

We currently have a couple of snake_case commands. This standardizes the
commands such that they are consistent.

feat!: Standardize on kebab-case for cli commands

---

CHANGELOG.md
setup.py
transcriptic/jupyter/objects.py

The current Kinetics.Spectrophotomery.plot function was broken.
Dropping support for older dependencies and updating them seems to be
the easiest solution to fixing this.

fix: Kinetics Spectrophotomery Plot

---

CHANGELOG.md
setup.py
transcriptic/analysis/spectrophotometry.py

The current Spectrophotometry.Absorbance, Fluorescence and Luminescence
plots were broken due to regressions in Matplotlib and Plotly.
As an additional fix, offline plots were enabled for Plotly for these
objects to keep them consistent with other plotly plots.

fix: Spectrophotometry PlateRead plots

---

CHANGELOG.md
transcriptic/config.py
transcriptic/jupyter/objects.py

With the new dataset embed representation, the previous default width is
too cramped. Increasing this to 600px seems reasonable and results in a
better view.

feat: Dataset Embed Representation

---

CHANGELOG.md
setup.py

As we're preparing for a major release, this is an opportunity to
upgrade some of our base dependencies.
This bumps our pytest dependency by one major version. Notably py35
support was dropped, and there has been multiple deprecations which we
are not affected by. There's also a bunch of bugfixes/improvements.
Pylint has been pinned to 2.5.2, which is the same as what we're running
in pre-commit.
Tox has been bumped to 3.15, which brings notable speedups.

build: Bump test dependencies

---

.pre-commit-config.yaml
CHANGELOG.rst
test/config_test.py
transcriptic/config.py
transcriptic/signing.py
transcriptic/util.py

We will soon be passing a client_credentials (service-to-service) bearer token to programs when executing in the context of Igor. Web will validate the bearer token (and only the bearer token, no user token needed) when receiving an API request.
Programs internally call the transcriptic library (this repo) to form an API `Connection`.
The change in this PR involves changing the Connection instantiation routine to recognize if the token is a `Bearer` token and, if so, set the standard OAuth `Authorization` header (and no `X-User-Token` header). This is opposed to a non-bearer token, which will result in the usual `X-User-Token` header.
Jira Issue: SEA-271

feat: Support Bearer Token Authentication

---

CHANGELOG.rst
test/config_test.py
transcriptic/auth.py
transcriptic/commands.py
transcriptic/config.py

See Jira issues for detailed description.
In a nutshell:
1. When bearer token auth or request signing is used, we set an authorization header for _all_ outgoing requests. This is problematic as we not only make requests to our own web endpoints, but also to S3, where it clashes with their query param auth scheme. The fix is to pass the `api_root` (e.g. https://secure.transcriptic.com) to the Signing initialization routine and only set the auth headers on outgoing requests that are destined for endpoints under our api_root.
2. When request signing is enabled, we encode the request body as part of determining the digest. It looks like for some calls (e.g. the POST with the data upload reference), the request body is already encoded (as `bytes`). So when we try to encode something that is …

Request Signing and Bearer Token Auth Issues: PP-2306 and PP-2307

---

.travis.yml
CHANGELOG.rst

Multiple deploy jobs are being spun for all tests running Python 3.6.
This adds an additional envvar filter to ensure we're only spinning off
a single deployment job.

build: Fix Travis deployment issue

---

.travis.yml
CHANGELOG.rst

Travis uses bash syntax for conditionals instead of its usual expressions syntax. See https://docs.travis-ci.com/user/deployment#conditional-releases-with-on
Tested this on a test repository.

build: Fix Travis bash syntax

---

CHANGELOG.rst
docs/conf.py
setup.py

We have a scipy dependency which is currently unused. The current
version bounds is causing downstream build errors for Py 37/38.

feat: Remove unused scipy dependency

---

CHANGELOG.rst
docs/objects.rst
transcriptic/jupyter/__init__.py
transcriptic/jupyter/common.py
transcriptic/jupyter/container.py
transcriptic/jupyter/dataobject.py
transcriptic/jupyter/dataset.py
transcriptic/jupyter/instruction.py
transcriptic/jupyter/project.py
transcriptic/jupyter/run.py

Part of a coming change to add sampledata to the module, let's first
breakout the Jupyter objects into individual python files for easier
comprehension.
This breaks existing direct imports from `transcriptic.jupyter.objects`
but that usage is very unusual. Usual imports like `from transcriptic
import *` and `from transcriptic.jupyter import Run` to access Jupyter
objects remains unaffected.

refactor: Breakout Jupyter objects

---

CHANGELOG.rst
CONTRIBUTING.rst
tox.ini

Plumbing posargs through would allow devs to run specific tests locally
using a tox environment.
Updated the documentation to reflect that pattern.

test: Plumb posargs through for tox

---

test/commands/exec_test.py
transcriptic/cli.py

When testing `transcriptic exec`, noticed that we are implicitly
requiring `api` option to be specified.
Not specifying `api` currently results in a non-helpful error message,
so this makes it explicitly required.

feat: Make api option required for exec

---

test/commands/exec_test.py
transcriptic/cli.py
transcriptic/commands.py

Summary:
The frontend url (lab.core.strateos.com/haven/wctest) is not the same that the url to the frontend node. This would be confusing to user to have to use different one.
The exec method will request the frontend server for the IP of the frontend node, and then make the request to it.
```
$ transcriptic preview Read | transcriptic exec --api http://lab.core.strateos.com/haven/wctest
Sending request to 13.52.223.111:9000
Success. View http://lab.core.strateos.com/haven/wctest/dashboard to see the scheduling outcome.
```

feature: handle new frontend deployment for frontend

---

CHANGELOG.rst
transcriptic/commands.py

**Background**
The protocol error `Protocol error: failed to generate a valid JSON response. See the info below for details.Please fix the above errors and try again.` in the program trace provide little information to debug. 
```
r1fqvwa5k56jrp
Program Trace
Searching for PostPurificationProcessing...
Protocol found.
Waiting for launch request to be configured.
Waiting for launch request to be configured..Attempting to fetch $1 datasets...
Collected 2.13 from ct1fqvvukvzahxk to ct1fmwmdhe7wwen
Collected 4.18 from ct1fqvvukvzahxk to ct1fmpmdhaf5v63
Collected 33.01 from ct1fqvvukvzahxk to ct1fmpmdhaun2ke
A SAP8-PO12 Run is going to be generated.
Protocol error: failed to generate a valid JSON response. See the info below for details.
Please fix the above errors and try again.
Uploaded …
```

STDV-806 stdout protocol generation error message info

---

CHANGELOG.rst
Dockerfile

Update base Python version to 3.7 and  pin nbgitpuller version

build: Update base Dockerfile   

---

CHANGELOG.rst
setup.py
transcriptic/analysis/spectrophotometry.py
transcriptic/commands.py
transcriptic/english.py
transcriptic/util.py

To upload the release archive to an org the POST data requires the `user_id` of the session.

fix: upload-release command api.post_release

---

CHANGELOG.rst
test/config_test.py
transcriptic/config.py

In this PR we change the preference from using the user token to preferring to user the bearer token. These changes also have to be used when we configure a Connection session in our current post-run programs -> https://github.com/strateos/internal_protocols/pull/759 , most post-run programs use the `internal_protocols/config/api.py` to configure their session connection.
https://strateos.atlassian.net/browse/STDV-1553

STDV-1553: Update Tx Connection API for permutations of setting auth

---

CHANGELOG.rst
transcriptic/commands.py

Update Transcriptic CLI to use "strateos" not "transcriptic" as default API root https://strateos.atlassian.net/browse/STDV-1817

Stdv-1817: Update Tx CLI to use "strateos" as default API root

---

.github/workflows/ci.yml
CHANGELOG.rst

We're seeing test failures in the CI due to being unable to resolve Python 3.6. This is due to using ubuntu-latest, which has dropped support for Python 3.6. 
Pin to the previous version of Ubuntu supporting 3.6, which is 20.04

build: Pin to Ubuntu 20.04 for CI

---

CHANGELOG.rst
test/config_test.py
transcriptic/auth.py
transcriptic/config.py

In the case where redirects are hit, we are currently following the default requests session rebuild_auth behavior which does not re-call any of our internal auth handlers.
This results in a case where a redirected request has a stale signature resulting in an auth error.

fix: Rebuild auth even on redirects
