strateos/transcriptic

setup.py
Adding `url` and `description` to `setup.py` so that can be picked up by `pypi`
=> Adding url and description to setup.py

setup.py, transcriptic/__init__.py, transcriptic/cli.py, transcriptic/objects.py
=> adding some more object types; need to return data from some functions

transcriptic/__init__.py, transcriptic/objects.py
=> fix the container() function

CHANGELOG.md, transcriptic/objects.py
Refactored Container object, added wellMap, aliquots properties, as well as automatically parsing and returning an autoprotocol.container_type.ContainerType object
=> Added functionality for Container object

transcriptic/analysis/spectrophotometry.py
This fixes spectrophotometry.py to account for new container formatting change
=> Fix spectrophotometry.py for new container formatting in datasets

transcriptic/objects.py
=> Add conditional to populate safe_min_volume_ul

CHANGELOG.md, transcriptic/cli.py
Summary:
Fixes T5243
- Updated behavior of `transcriptic login` to be clearer and to return appropriate error messages
- print statement for launch
Test Plan: Tested with valid and invalid option inputs
Reviewers: peter
Subscribers: Benjamin
Maniphest Tasks: T5243
Differential Revision: https://work.r23s.net/D4421
=> Update Transcriptic Login description to be clearer

.gitignore, transcriptic/__init__.py, transcriptic/analysis/spectrophotometry.py, transcriptic/cli.py, transcriptic/config.py, transcriptic/english.py, transcriptic/objects.py, transcriptic/util.py
Reformat to ensure PEP8 compatibility
=> PEP 8 reformat and removing unused imports

CHANGELOG.md, setup.py
Bump version since datasets route fix is of high importance
=> version bump to 2.1.2

CHANGELOG.md, setup.py
bumping version in line with the major API refactoring
=> version bump to 2.2.0

CHANGELOG.md, setup.py, transcriptic/objects.py
Version bump to v2.1.1 to address bugfixes and add python2/3 compatibility
=> Version Bump to 2.1.1

CHANGELOG.md, transcriptic/__init__.py, transcriptic/objects.py, transcriptic/routes.py
Changed
- Reworked `Instruction` object
- Reworked `Run.instructions` to return a Dataframe of `Instruction` objects
- `Aliquot` object has been reworked into Container object as an `aliquots` property
Removed
- `Resource` object has been removed from the library as its currently unused
=> Refactor Instruction, Aliquot and Resource objects

CHANGELOG.md, pytest.ini, setup.py, test/AP2En_test.py, test/autoprotocol/longrun.json, transcriptic/cli.py, transcriptic/english.py
The following changes include additions to cli.py's summarize function and english.py's AutoprotocolParser class — specifically, the addition of job tree construction method and the update of all English instructions currently implemented. Tested against custom tests and well as the tox suite.
=> Added Job Tree Functionality and Updated Summarize

.gitignore, transcriptic/config.py, transcriptic/routes.py
API structure changed a little bit, this reflects new reality.
=> Fix runs-by-project route

CHANGELOG.md, transcriptic/objects.py
WIP
Functionality in place but no version bump and no test coverage.
=> added support for getting run containers from Run object

CHANGELOG.md, transcriptic/config.py, transcriptic/objects.py, transcriptic/routes.py
- Change monitoring data route to reflect product changes
- Shift `monitoring` method from `Run` object to `Instruction` object
- Misc. PEP8 changes to objects.py and add in support for optional parameters in routes
=> Update Monitoring Data

CHANGELOG.md, transcriptic/objects.py
Added
- Row index of the Container.aliquots DataFrame object now corresponds to the well index
=> Return well index as part of aliquots DataFrame for the container

CHANGELOG.md, transcriptic/config.py, transcriptic/objects.py
This pull request adds support for more intuitive object selection. For example, you can now do enter `myRun.Instructions`, and it will have the same effect as entering `myRun.instructions.Instructions`. 
There are a few minor bugfixes and updates
=> Object helpers

CHANGELOG.md, transcriptic/cli.py, transcriptic/config.py, transcriptic/objects.py, transcriptic/routes.py
This diff adds support launching remote protocols by adding the `--remote` flag to both `transcriptic launch` and `transcriptic protocols`
=> Add support for launching remote protocols

CHANGELOG.md, transcriptic/objects.py
Adds ability to cross reference data with aliquots in the Dataset object
=> Cross reference aliquots with data

CHANGELOG.md, transcriptic/config.py
This brings two updates to the `api` object. 
Firstly, the underlying connection is now maintained using a requests.Session object. This helps maintain a persistent HTTP connection which should speed up requests in general.
Secondly, the `api` object now has more formal support for cookie-based authentication.
=> Maintain persistent connection, update cookie-based auth

transcriptic/cli.py, transcriptic/config.py, transcriptic/routes.py
Summary:
Opens up the webapp and shows an embedded RunInstructions page.
depends on D9173
Test Plan:
After web changes:
transcriptic preview foo | transcriptic summarize --html
Reviewers: yangchoo, peter
Differential Revision: https://work.r23s.net/D9174
=> Add html summary view.

Dockerfile
Summary: Fix setuptools failure
Test Plan: Jenkins
Reviewers: yangchoo, rhys, varun
Differential Revision: https://work.r23s.net/D10334
=> Fix Jenkins setuptools fail

CHANGELOG.md, docs/conf.py, docs/index.rst, docs/objects.rst, transcriptic/config.py
This PR updates some static doc files that were causing docs to not build properly
=> Fix doc building

.pylintrc, .travis.yml, CHANGELOG.md, setup.py, test/api_test.py, test/conftest.py, test/helpers/protocol_response.py, tox.ini, transcriptic/__init__.py, transcriptic/analysis/imaging.py, transcriptic/analysis/spectrophotometry.py, transcriptic/cli.py, transcriptic/commands.py, transcriptic/util.py
- add travis support
- build docs and lint when running tox
- clean up dependencies
- fix broken imports and unresolved references surfaced by pylint
=> Build improvements

CHANGELOG.md, transcriptic/config.py, transcriptic/jupyter/objects.py, transcriptic/routes.py
Summary: Makes fetching Data Objects easier.
=> Add helpers for fetching data objects.

CHANGELOG.md, transcriptic/cli.py, transcriptic/commands.py
https://strateos.atlassian.net/browse/STDEV-29?atlOrigin=eyJpIjoiZTc3Y2M5ZGIzZTZlNGVjNmFkZjJjM2NhMjI2ZTBmNTEiLCJwIjoiaiJ9
=> Add run title to launch

.travis.yml, CHANGELOG.md
Adds a travis deploy job to automate deployment to pypi and github
releases
=> build: add travis deploy

.travis.yml, CHANGELOG.md, setup.py, test/helpers/protocol_response.py, transcriptic/analysis/kinetics.py, transcriptic/analysis/spectrophotometry.py, transcriptic/commands.py, transcriptic/config.py, transcriptic/english.py, transcriptic/jupyter/objects.py, transcriptic/signing.py, transcriptic/util.py
Upgrade base Python version to Python 3.6, standardize string formatting
on f-string interpolation.
String formatting auto-fix done with flynt and manually checked.
=> build: Upgrade python version to 3.6

CHANGELOG.rst, setup.py, tox.ini, transcriptic/analysis/spectrophotometry.py, transcriptic/config.py, transcriptic/util.py
Summary:
Support for 1536w containers in transcriptic autoprotocol python
Refactored to use APPY static methods for robotize and humanize
Linked task: https://strateos.atlassian.net/browse/OX-62
=> feat: support 1536w container types

.pre-commit-config.yaml, CHANGELOG.rst, transcriptic/analysis/spectrophotometry.py, transcriptic/cli.py, transcriptic/commands.py, transcriptic/routes.py
We're using the stable branch of black which can cause some local dev
env inconsistency with Travis. This pins the version to 20.8b1.
=> style: Pin Black to 20.8b1

.travis.yml, CHANGELOG.rst, README.rst, tox.ini
Add codecov step to generate code coverage badge.
Add stats_xml step in tox to create xml format required by codecov.
=> build: Add codecov configuration

CHANGELOG.rst, notebooks/objects.ipynb
Add example notebook showcasing how to use the Transcriptic library for
objects.
=> doc: add example object notebook

CHANGELOG.rst, Dockerfile, README.rst
Update dockerfile and add Binder badge.
=> feat: Add Binder

CHANGELOG.rst, README.rst
Add downloads badge so that we can keep track of usage rate of this
package.
=> build: Add Downloads Badge

.github/workflows/ci.yml, CHANGELOG.rst
=> build: Add CodeCov

transcriptic/cli.py, transcriptic/commands.py
https://github.com/strateos/lab/pull/1496
```
$ transcriptic preview Seal | transcriptic exec --api localhost:9000 --no-redirect -w wc0-mcx1
Sending request to localhost:9000
Success. View localhost:9000/dashboard to see the scheduling outcome.
$ transcriptic preview Seal | transcriptic exec --api localhost:9000 --no-redirect -w wc0-mcx1 -tc-suggestion
Sending request to localhost:9000
Success. View localhost:9000/dashboard to see the scheduling outcome.
$ transcriptic preview Seal | transcriptic exec --api localhost:9000 -w wc0-mcx1 -tc-suggestion
Invalid api target, expects http://base/facility/workcell.
```
=> feature: add tc are suggestions in exec

CHANGELOG.rst, setup.py
Update requests package to avoid dependencies conflicts
=> update: requests>2.21.0
